/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LIBRERIAS = 7;
  /** RegularExpression Id. */
  int MAIN = 8;
  /** RegularExpression Id. */
  int RETURN = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int FLOAT = 11;
  /** RegularExpression Id. */
  int CHAR = 12;
  /** RegularExpression Id. */
  int BOOLEAN = 13;
  /** RegularExpression Id. */
  int SHORT = 14;
  /** RegularExpression Id. */
  int STRING = 15;
  /** RegularExpression Id. */
  int DOUBLE = 16;
  /** RegularExpression Id. */
  int VOID = 17;
  /** RegularExpression Id. */
  int SUMA = 18;
  /** RegularExpression Id. */
  int RESTA = 19;
  /** RegularExpression Id. */
  int MULTIPLICACION = 20;
  /** RegularExpression Id. */
  int ASIGNAR = 21;
  /** RegularExpression Id. */
  int DIVISION = 22;
  /** RegularExpression Id. */
  int MODULO = 23;
  /** RegularExpression Id. */
  int INCREMENTO = 24;
  /** RegularExpression Id. */
  int DECREMENTO = 25;
  /** RegularExpression Id. */
  int FOR = 26;
  /** RegularExpression Id. */
  int WHILE = 27;
  /** RegularExpression Id. */
  int DO = 28;
  /** RegularExpression Id. */
  int IF = 29;
  /** RegularExpression Id. */
  int ELSE = 30;
  /** RegularExpression Id. */
  int SWITCH = 31;
  /** RegularExpression Id. */
  int CASE = 32;
  /** RegularExpression Id. */
  int BREAK = 33;
  /** RegularExpression Id. */
  int SCANF = 34;
  /** RegularExpression Id. */
  int PRINTF = 35;
  /** RegularExpression Id. */
  int IGUAL = 36;
  /** RegularExpression Id. */
  int DIFERENTE = 37;
  /** RegularExpression Id. */
  int MENOR = 38;
  /** RegularExpression Id. */
  int MAYOR = 39;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 40;
  /** RegularExpression Id. */
  int MAYOR_IGUAL = 41;
  /** RegularExpression Id. */
  int AMPERSAND = 42;
  /** RegularExpression Id. */
  int AND = 43;
  /** RegularExpression Id. */
  int OR = 44;
  /** RegularExpression Id. */
  int NOT = 45;
  /** RegularExpression Id. */
  int LLAVE_APERTURA = 46;
  /** RegularExpression Id. */
  int LLAVE_CIERRE = 47;
  /** RegularExpression Id. */
  int PARENTESIS_APERTURA = 48;
  /** RegularExpression Id. */
  int PARENTESIS_CIERRE = 49;
  /** RegularExpression Id. */
  int PUNTO_COMA = 50;
  /** RegularExpression Id. */
  int CORCHETE_APERTURA = 51;
  /** RegularExpression Id. */
  int CORCHETE_CIERRE = 52;
  /** RegularExpression Id. */
  int COMA = 53;
  /** RegularExpression Id. */
  int PUNTO = 54;
  /** RegularExpression Id. */
  int DOS_PUNTOS = 55;
  /** RegularExpression Id. */
  int NOMBREVAR = 56;
  /** RegularExpression Id. */
  int CADENA = 57;
  /** RegularExpression Id. */
  int NUMEROS = 58;
  /** RegularExpression Id. */
  int DECIMALES = 59;
  /** RegularExpression Id. */
  int NOMLIBRERIA = 60;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"#include\"",
    "\"main\"",
    "\"return\"",
    "\"int\"",
    "\"float\"",
    "\"char\"",
    "\"bool\"",
    "\"short\"",
    "\"string\"",
    "\"double\"",
    "\"void\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"=\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"for\"",
    "\"while\"",
    "\"do\"",
    "\"if\"",
    "\"else\"",
    "\"switch\"",
    "\"case\"",
    "\"break\"",
    "\"scanf\"",
    "\"printf\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "<NOMBREVAR>",
    "<CADENA>",
    "<NUMEROS>",
    "<DECIMALES>",
    "<NOMLIBRERIA>",
  };

}
